/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _font8_h_
#define _font8_h_
//---------------------------------------------------------------------------------
extern const unsigned char font8[];
extern const int font8_char_high;
extern const int font8_char_width;
//---------------------------------------------------------------------------------
#endif //_font8_h_
//---------------------------------------------------------------------------------